# File: src/main/resources/application.yml
server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/goodeats
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true