# File: src/main/resources/application.yml
server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: restaurant-service
  data:
    mongodb:
      uri: mongodb+srv://elliebyrne:GoodEats@cluster0.tp763.mongodb.net/GoodEats?retryWrites=true&w=majority&appName=Cluster0
      database: GoodEats
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true