server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: restaurant-service
  data:
    mongodb:
      uri: mongodb+srv://elliebyrne:GoodEats@cluster0.tp763.mongodb.net/GoodEats
      database: GoodEats
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG