#pipeline
name: GoodEats CI/CD Pipeline
on:
  release:
    types: [created]
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Validate HTML/CSS
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard
          find backend/src/main/resources/static -name "*.html" -exec htmlhint {} \;
          find backend/src/main/resources/static -name "*.css" -exec stylelint {} \;

      - name: Package with Maven
        run: mvn -B package --file backend/pom.xml -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: goodEats-package
          path: backend/target/*.jar

      # Only deploy to GitHub Packages on release or main branch
      - name: Publish to GitHub Packages
        if: github.event_name == 'release' || github.ref == 'refs/heads/main'
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -f backend/pom.xml -DskipTests
        env:
          GITHUB_TOKEN: ${{ github.token }}