# MongoDB connection settings
spring.data.mongodb.uri=mongodb+srv://elliebyrne:GoodEats@cluster0.tp763.mongodb.net/London?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=London

# Enable logging to see what's happening
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.example=DEBUG

# Server port (default is 8080)
server.port=8080